## -*- encoding: utf-8 -*-
## This file (answerBox.sagetex.sage) was *autogenerated* from answerBox.tex with sagetex.sty version 2019/11/14 v3.4.
import sagetex
_st_ = sagetex.SageTeXProcessor('answerBox', version='2019/11/14 v3.4', version_check=True)
_st_.endofdoc()
