## -*- encoding: utf-8 -*-


# This file was *autogenerated* from the file selectAll.sagetex.sage
from sage.all_cmdline import *   # import sage library

## This file (selectAll.sagetex.sage) was *autogenerated* from selectAll.tex with sagetex.sty version 2019/11/14 v3.4.
import sagetex
_st_ = sagetex.SageTeXProcessor('selectAll', version='2019/11/14 v3.4', version_check=True)
_st_.endofdoc()

