## -*- encoding: utf-8 -*-


# This file was *autogenerated* from the file hiddenAnswers.sagetex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_65 = Integer(65); _sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_4 = Integer(4); _sage_const_70 = Integer(70); _sage_const_72 = Integer(72); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1)## This file (hiddenAnswers.sagetex.sage) was *autogenerated* from hiddenAnswers.tex with sagetex.sty version 2019/11/14 v3.4.
import sagetex
_st_ = sagetex.SageTeXProcessor('hiddenAnswers', version='2019/11/14 v3.4', version_check=True)
_st_.current_tex_line = _sage_const_65 
_st_.blockbegin()
try:
         p1c1 = _sage_const_3 
         p1f1 = _sage_const_2 *x + _sage_const_4 
 
         p1ans = p1f1(x=p1c1)
     
except:
 _st_.goboom(_sage_const_70 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_72 
 _st_.inline(_sage_const_0 , latex(p1f1))
except:
 _st_.goboom(_sage_const_72 )
try:
 _st_.current_tex_line = _sage_const_72 
 _st_.inline(_sage_const_1 , latex(p1c1))
except:
 _st_.goboom(_sage_const_72 )
try:
 _st_.current_tex_line = _sage_const_72 
 _st_.inline(_sage_const_2 , latex(p1ans))
except:
 _st_.goboom(_sage_const_72 )
_st_.endofdoc()

