## -*- encoding: utf-8 -*-
## This file (randomizedGraphing.sagetex.sage) was *autogenerated* from randomizedGraphing.tex with sagetex.sty version 2019/11/14 v3.4.
import sagetex
_st_ = sagetex.SageTeXProcessor('randomizedGraphing', version='2019/11/14 v3.4', version_check=True)
try:
 _st_.current_tex_line = 74
 _st_.inline(0, p1temp1)
except:
 _st_.goboom(74)
_st_.endofdoc()
