## -*- encoding: utf-8 -*-
## This file (randomizingWithSage.sagetex.sage) was *autogenerated* from randomizingWithSage.tex with sagetex.sty version 2019/11/14 v3.4.
import sagetex
_st_ = sagetex.SageTeXProcessor('randomizingWithSage', version='2019/11/14 v3.4', version_check=True)
_st_.endofdoc()
