## -*- encoding: utf-8 -*-


# This file was *autogenerated* from the file randomizingWithSage.sagetex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_67 = Integer(67); _sage_const_0 = Integer(0); _sage_const_10 = Integer(10); _sage_const_5 = Integer(5); _sage_const_93 = Integer(93); _sage_const_97 = Integer(97)## This file (randomizingWithSage.sagetex.sage) was *autogenerated* from randomizingWithSage.tex with sagetex.sty version 2019/11/14 v3.4.
import sagetex
_st_ = sagetex.SageTeXProcessor('randomizingWithSage', version='2019/11/14 v3.4', version_check=True)
_st_.current_tex_line = _sage_const_67 
_st_.blockbegin()
try:
 #####Define default Sage variables.
 #Default function variables
 var('x,y,z,X,Y,Z,r,R')
 #Default function names
 var('f,g,h,dx,dy,dz,dh,df')
 
 def RandInt(a,b):
     """ Returns a random integer in [`a`,`b`]. Note that `a` and `b` should be integers themselves to avoid unexpected behavior.
     """
     return QQ(randint(int(a),int(b)))
     # return choice(range(a,b+1))
 
 def NonZeroInt(b,c, avoid = [_sage_const_0 ]):
     """ Returns a random integer in [`b`,`c`] which is not in `av`.
         If `av` is not specified, defaults to a non-zero integer.
     """
     while True:
         a = RandInt(b,c)
         if a not in avoid:
             return a
 
 p1c1 = NonZeroInt(-_sage_const_10 ,_sage_const_10 )
 p1c2 = RandInt(-_sage_const_5 ,_sage_const_5 )
 p1c3 = RandInt(-_sage_const_5 ,_sage_const_5 )
 p1f1 = expand( (p1c1*x-p1c2)*(x-p1c3) )
     
except:
 _st_.goboom(_sage_const_93 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_97 
 _st_.inline(_sage_const_0 , latex(p1f1))
except:
 _st_.goboom(_sage_const_97 )
_st_.endofdoc()

