## -*- encoding: utf-8 -*-


# This file was *autogenerated* from the file sageCommands.sagetex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_35 = Integer(35); _sage_const_3 = Integer(3); _sage_const_1 = Integer(1); _sage_const_4 = Integer(4); _sage_const_38 = Integer(38); _sage_const_40 = Integer(40); _sage_const_0 = Integer(0); _sage_const_127 = Integer(127); _sage_const_130 = Integer(130); _sage_const_134 = Integer(134); _sage_const_2 = Integer(2); _sage_const_137 = Integer(137); _sage_const_161 = Integer(161); _sage_const_164 = Integer(164); _sage_const_168 = Integer(168); _sage_const_171 = Integer(171); _sage_const_5 = Integer(5)## This file (sageCommands.sagetex.sage) was *autogenerated* from sageCommands.tex with sagetex.sty version 2019/11/14 v3.4.
import sagetex
_st_ = sagetex.SageTeXProcessor('sageCommands', version='2019/11/14 v3.4', version_check=True)
_st_.current_tex_line = _sage_const_35 
_st_.blockbegin()
try:
 p2f1 = _sage_const_3 *x+_sage_const_1 
 p2ans = p2f1(x=_sage_const_4 )
except:
 _st_.goboom(_sage_const_38 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_40 
 _st_.inline(_sage_const_0 , latex(p2f1))
except:
 _st_.goboom(_sage_const_40 )
try:
 _st_.current_tex_line = _sage_const_40 
 _st_.inline(_sage_const_1 , latex(p2ans))
except:
 _st_.goboom(_sage_const_40 )
_st_.current_tex_line = _sage_const_127 
_st_.blockbegin()
try:
 p4str = 'this is a string'
 p4ans = 'yes'
except:
 _st_.goboom(_sage_const_130 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_134 
 _st_.inline(_sage_const_2 , latex(p4str))
except:
 _st_.goboom(_sage_const_134 )
try:
 _st_.current_tex_line = _sage_const_137 
 _st_.inline(_sage_const_3 , latex(p4ans))
except:
 _st_.goboom(_sage_const_137 )
_st_.current_tex_line = _sage_const_161 
_st_.blockbegin()
try:
 p5str = LatexExpr(r'\text{this is a string}')
 p5ans = LatexExpr(r'yes')
except:
 _st_.goboom(_sage_const_164 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_168 
 _st_.inline(_sage_const_4 , latex(p5str))
except:
 _st_.goboom(_sage_const_168 )
try:
 _st_.current_tex_line = _sage_const_171 
 _st_.inline(_sage_const_5 , latex(p5ans))
except:
 _st_.goboom(_sage_const_171 )
_st_.endofdoc()

