## -*- encoding: utf-8 -*-


# This file was *autogenerated* from the file factorCheck.sagetex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_426 = Integer(426); _sage_const_0 = Integer(0); _sage_const_5 = Integer(5); _sage_const_3 = Integer(3); _sage_const_467 = Integer(467); _sage_const_471 = Integer(471); _sage_const_473 = Integer(473); _sage_const_1 = Integer(1)## This file (factorCheck.sagetex.sage) was *autogenerated* from factorCheck.tex with sagetex.sty version 2019/11/14 v3.4.
import sagetex
_st_ = sagetex.SageTeXProcessor('factorCheck', version='2019/11/14 v3.4', version_check=True)
_st_.current_tex_line = _sage_const_426 
_st_.blockbegin()
try:
 def RandInt(a,b):
     """ Returns a random integer in [`a`,`b`]. Note that `a` and `b` should be integers themselves to avoid unexpected behavior.
     """
     return QQ(randint(int(a),int(b)))
     # return choice(range(a,b+1))
 
 def NonZeroInt(b,c, avoid = [_sage_const_0 ]):
     """ Returns a random integer in [`b`,`c`] which is not in `av`.
         If `av` is not specified, defaults to a non-zero integer.
     """
     while True:
         a = RandInt(b,c)
         if a not in avoid:
             return a
 
 p1c1 = NonZeroInt(-_sage_const_5 ,_sage_const_5 )
 p1c2 = RandInt(-_sage_const_5 ,_sage_const_5 )
 p1c3 = NonZeroInt(-_sage_const_5 ,_sage_const_5 )
 p1c4 = RandInt(-_sage_const_5 ,_sage_const_5 )
 p1c5 = NonZeroInt(-_sage_const_5 ,_sage_const_5 )
 p1c6 = RandInt(-_sage_const_5 ,_sage_const_5 )
 p1c7 = NonZeroInt(-_sage_const_5 ,_sage_const_5 )
 p1c8 = RandInt(-_sage_const_5 ,_sage_const_5 )
 p1c9 = NonZeroInt(-_sage_const_5 ,_sage_const_5 )
 p1c10 = RandInt(-_sage_const_5 ,_sage_const_5 )
 p1c11 = NonZeroInt(-_sage_const_5 ,_sage_const_5 )
 p1c12 = RandInt(-_sage_const_5 ,_sage_const_5 )
 p1c13 = NonZeroInt(-_sage_const_5 ,_sage_const_5 )
 p1c14 = RandInt(-_sage_const_5 ,_sage_const_5 )
 
 p1f1 = p1c1*x-p1c2
 p1f2 = p1c3*x-p1c4
 p1f3 = p1c5*x-p1c6
 p1f4 = p1c7*x-p1c8
 p1f5 = p1c9*x-p1c10
 p1f6 = p1c11*x-p1c12
 p1f7 = p1c13*x-p1c14
 
 p1fdisp = x**_sage_const_3 *p1f1*p1f2*p1f3*p1f4*p1f5*p1f6*p1f7
 
except:
 _st_.goboom(_sage_const_467 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_471 
 _st_.inline(_sage_const_0 , latex(p1fdisp))
except:
 _st_.goboom(_sage_const_471 )
try:
 _st_.current_tex_line = _sage_const_473 
 _st_.inline(_sage_const_1 , latex(p1fdisp))
except:
 _st_.goboom(_sage_const_473 )
_st_.endofdoc()

