## -*- encoding: utf-8 -*-
## This file (targetedFeedback.sagetex.sage) was *autogenerated* from targetedFeedback.tex with sagetex.sty version 2019/11/14 v3.4.
import sagetex
_st_ = sagetex.SageTeXProcessor('targetedFeedback', version='2019/11/14 v3.4', version_check=True)
_st_.endofdoc()
