## -*- encoding: utf-8 -*-


# This file was *autogenerated* from the file multipleChoice.sagetex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_23 = Integer(23); _sage_const_0 = Integer(0); _sage_const_10 = Integer(10); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_5 = Integer(5); _sage_const_56 = Integer(56); _sage_const_60 = Integer(60); _sage_const_63 = Integer(63); _sage_const_64 = Integer(64); _sage_const_65 = Integer(65); _sage_const_3 = Integer(3); _sage_const_66 = Integer(66); _sage_const_4 = Integer(4); _sage_const_67 = Integer(67); _sage_const_69 = Integer(69); _sage_const_6 = Integer(6); _sage_const_84 = Integer(84); _sage_const_7 = Integer(7); _sage_const_87 = Integer(87); _sage_const_8 = Integer(8); _sage_const_88 = Integer(88); _sage_const_9 = Integer(9); _sage_const_89 = Integer(89); _sage_const_90 = Integer(90); _sage_const_11 = Integer(11); _sage_const_91 = Integer(91); _sage_const_12 = Integer(12); _sage_const_94 = Integer(94); _sage_const_13 = Integer(13); _sage_const_104 = Integer(104); _sage_const_14 = Integer(14); _sage_const_15 = Integer(15); _sage_const_107 = Integer(107); _sage_const_16 = Integer(16); _sage_const_108 = Integer(108); _sage_const_17 = Integer(17); _sage_const_109 = Integer(109); _sage_const_18 = Integer(18); _sage_const_110 = Integer(110); _sage_const_19 = Integer(19); _sage_const_111 = Integer(111); _sage_const_20 = Integer(20); _sage_const_114 = Integer(114); _sage_const_21 = Integer(21)## This file (multipleChoice.sagetex.sage) was *autogenerated* from multipleChoice.tex with sagetex.sty version 2019/11/14 v3.4.
import sagetex
_st_ = sagetex.SageTeXProcessor('multipleChoice', version='2019/11/14 v3.4', version_check=True)
_st_.current_tex_line = _sage_const_23 
_st_.blockbegin()
try:
 def RandInt(a,b):
     """ Returns a random integer in [`a`,`b`]. Note that `a` and `b` should be integers themselves to avoid unexpected behavior.
     """
     return QQ(randint(int(a),int(b)))
     # return choice(range(a,b+1))
 
 def NonZeroInt(b,c, avoid = [_sage_const_0 ]):
     """ Returns a random integer in [`b`,`c`] which is not in `av`.
         If `av` is not specified, defaults to a non-zero integer.
     """
     while True:
         a = RandInt(b,c)
         if a not in avoid:
             return a
 
 p1c1 = RandInt(-_sage_const_10 ,_sage_const_10 )
 p1c2 = NonZeroInt(-_sage_const_10 ,_sage_const_10 ,[p1c1])
 p1c3 = NonZeroInt(-_sage_const_10 ,_sage_const_10 ,[p1c1,p1c2])
 p1c4 = NonZeroInt(-_sage_const_10 ,_sage_const_10 ,[p1c1,p1c2,p1c3])
 p1c5 = NonZeroInt(-_sage_const_10 ,_sage_const_10 ,[p1c1,p1c2,p1c3,p1c4])
 
 p1ansvec = [p1c1,p1c2,p1c3,p1c4,p1c5]
 shuffle(p1ansvec)
 
 p1ans1 = p1ansvec.index(p1c1) + _sage_const_1 
 
 p1ans2 = _sage_const_2 **_sage_const_5 -_sage_const_1 -_sage_const_2 **(p1ansvec.index(p1c1))
 
 p1ansvecalpha=[LatexExpr(r"a"),LatexExpr(r"b"),LatexExpr(r"c"),LatexExpr(r"d"),LatexExpr(r"e")]
 
 p1ans3 = p1ansvecalpha[p1ansvec.index(p1c2)]+p1ansvecalpha[p1ansvec.index(p1c3)]
 
except:
 _st_.goboom(_sage_const_56 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_60 
 _st_.inline(_sage_const_0 , latex(p1c1))
except:
 _st_.goboom(_sage_const_60 )
try:
 _st_.current_tex_line = _sage_const_63 
 _st_.inline(_sage_const_1 , latex(p1ansvec[_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_63 )
try:
 _st_.current_tex_line = _sage_const_64 
 _st_.inline(_sage_const_2 , latex(p1ansvec[_sage_const_1 ]))
except:
 _st_.goboom(_sage_const_64 )
try:
 _st_.current_tex_line = _sage_const_65 
 _st_.inline(_sage_const_3 , latex(p1ansvec[_sage_const_2 ]))
except:
 _st_.goboom(_sage_const_65 )
try:
 _st_.current_tex_line = _sage_const_66 
 _st_.inline(_sage_const_4 , latex(p1ansvec[_sage_const_3 ]))
except:
 _st_.goboom(_sage_const_66 )
try:
 _st_.current_tex_line = _sage_const_67 
 _st_.inline(_sage_const_5 , latex(p1ansvec[_sage_const_4 ]))
except:
 _st_.goboom(_sage_const_67 )
try:
 _st_.current_tex_line = _sage_const_69 
 _st_.inline(_sage_const_6 , latex(p1ans1))
except:
 _st_.goboom(_sage_const_69 )
try:
 _st_.current_tex_line = _sage_const_84 
 _st_.inline(_sage_const_7 , latex(p1c1))
except:
 _st_.goboom(_sage_const_84 )
try:
 _st_.current_tex_line = _sage_const_87 
 _st_.inline(_sage_const_8 , latex(p1ansvec[_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_87 )
try:
 _st_.current_tex_line = _sage_const_88 
 _st_.inline(_sage_const_9 , latex(p1ansvec[_sage_const_1 ]))
except:
 _st_.goboom(_sage_const_88 )
try:
 _st_.current_tex_line = _sage_const_89 
 _st_.inline(_sage_const_10 , latex(p1ansvec[_sage_const_2 ]))
except:
 _st_.goboom(_sage_const_89 )
try:
 _st_.current_tex_line = _sage_const_90 
 _st_.inline(_sage_const_11 , latex(p1ansvec[_sage_const_3 ]))
except:
 _st_.goboom(_sage_const_90 )
try:
 _st_.current_tex_line = _sage_const_91 
 _st_.inline(_sage_const_12 , latex(p1ansvec[_sage_const_4 ]))
except:
 _st_.goboom(_sage_const_91 )
try:
 _st_.current_tex_line = _sage_const_94 
 _st_.inline(_sage_const_13 , latex(p1ans2))
except:
 _st_.goboom(_sage_const_94 )
try:
 _st_.current_tex_line = _sage_const_104 
 _st_.inline(_sage_const_14 , latex(p1c2))
except:
 _st_.goboom(_sage_const_104 )
try:
 _st_.current_tex_line = _sage_const_104 
 _st_.inline(_sage_const_15 , latex(p1c3))
except:
 _st_.goboom(_sage_const_104 )
try:
 _st_.current_tex_line = _sage_const_107 
 _st_.inline(_sage_const_16 , latex(p1ansvec[_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_107 )
try:
 _st_.current_tex_line = _sage_const_108 
 _st_.inline(_sage_const_17 , latex(p1ansvec[_sage_const_1 ]))
except:
 _st_.goboom(_sage_const_108 )
try:
 _st_.current_tex_line = _sage_const_109 
 _st_.inline(_sage_const_18 , latex(p1ansvec[_sage_const_2 ]))
except:
 _st_.goboom(_sage_const_109 )
try:
 _st_.current_tex_line = _sage_const_110 
 _st_.inline(_sage_const_19 , latex(p1ansvec[_sage_const_3 ]))
except:
 _st_.goboom(_sage_const_110 )
try:
 _st_.current_tex_line = _sage_const_111 
 _st_.inline(_sage_const_20 , latex(p1ansvec[_sage_const_4 ]))
except:
 _st_.goboom(_sage_const_111 )
try:
 _st_.current_tex_line = _sage_const_114 
 _st_.inline(_sage_const_21 , latex(p1ans3))
except:
 _st_.goboom(_sage_const_114 )
_st_.endofdoc()

