name: PushGitlab

on:
  push:
    branches: [ tests_basic ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with: 
        fetch-depth: 0
    - name: Add SSH key
      env:
                  SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
                  mkdir -p /home/runner/.ssh
                  ssh-keyscan gitlab.kuleuven.be >> /home/runner/.ssh/known_hosts
                  # SSH_KEY is the name of the repository secret
                  echo "${{ secrets.XIMERA_SSH_KEY }}" > /home/runner/.ssh/id_ed25519
                  chmod 600 /home/runner/.ssh/id_ed25519
    - name: Push To Gitlab
      run: |
        echo Starting to push repo to gitlab
        git config user.name "FromGithub"
        git config user.email "FromGithub@nowhere.com"
        #  git config core.sshCommand "ssh -v"
        git remote set-url origin "git@gitlab.kuleuven.be:monitoraat-wet/ximera/examples.git"
        echo Get updates
        git pull --no-rebase
        echo Set remote
        git push -f origin tests_basic
        rm -f /home/runner/.ssh/id_ed25519
